title: Cayman theme
description: This portfolio reflects my data analytics/science journey, showcasing projects that exhibit my adeptness in data manipulation, statistical analysis software, exploratory data analysis, and creating interactive visualizations.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
